name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read
  issues: read
  statuses: write

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setting Permissions
        run: chmod a+x gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          
      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
          
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
        
      - name: Download previous badges
        uses: actions/download-artifact@v3
        with:
          name: jacoco-badge-data
          path: .github/badges
        continue-on-error: true
      
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          fail-on-coverage-decrease: true
          fail-on-branches-decrease: true
          generate-coverage-badge: true
          generate-branches-badge: true
          generate-summary: true
          
      - name: Upload JaCoCo badges
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-badge-data
          path: .github/badges
          
      # Print out coverage info for debugging
      - name: Output Coverage Info
        run: |
          echo "Coverage: ${{ steps.jacoco.outputs.coverage }}"
          echo "Previous Coverage: ${{ steps.jacoco.outputs.coverage-percent-previous }}"
          echo "Branch Coverage: ${{ steps.jacoco.outputs.branches }}"
          echo "Previous Branch Coverage: ${{ steps.jacoco.outputs.branches-percent-previous }}"
          cat .github/badges/jacoco.json || echo "No coverage JSON found"

  build_and_publish_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
